version: "3.6"

services:
        nginx:
               container_name: nginx
               build: requirements/nginx
               image: nginx:inception
               depends_on: [mariadb, wordpress]
               restart: always
               env_file: ./.env
               ports:
                       - "8081:8080"
                       - "7979:7979"
               networks:
                       gen-network:
                               aliases:
                                       - bdetune.42.fr
               volumes:
                       - www-volume:/var/html/www
networks:
        gen-network: {}

volumes:
        www-volume:
